# theme =========================================================================================

theme = "evergarden_fall_green"

# editor ========================================================================================

[editor]
atomic-save = true
editor-config = true

text-width = 97
default-line-ending = "lf"
trim-trailing-whitespace = true
trim-final-newlines = true
insert-final-newline = true

# mouse =========================================================================================

scrolloff = 5
scroll-lines = 3

mouse = false
middle-click-paste = false

# terminal ======================================================================================

true-color = false
undercurl = false

# layout ========================================================================================

cursorline = false
cursorcolumn = false

popup-border = "none"
bufferline = "multiple"
line-number = "absolute"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

# completion ====================================================================================

auto-completion = true
path-completion = true
completion-replace = false
preview-completion-insert = true
completion-trigger-len = 2

completion-timeout = 50
idle-timeout = 250

# helpers =======================================================================================

indent-heuristic = "hybrid"
continue-comments = false

auto-format = true
auto-info = true

# lsp ===========================================================================================

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = false
auto-signature-help = true
display-inlay-hints = false
display-color-swatches = true
display-signature-help-docs = true
goto-reference-include-declaration = true
snippets = true

# file picker ===================================================================================

[editor.file-picker]
hidden = false
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
follow-symlinks = true
deduplicate-links = true

# diagnostics ===================================================================================

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"
prefix-len = 1
max-wrap = 20
max-diagnostics = 5

# search ========================================================================================

[editor.search]
smart-case = true
wrap-around = true

# wrapping ======================================================================================

[editor.soft-wrap]
enable = false

# auto pairs ====================================================================================

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

# whitespace ====================================================================================

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"

[editor.whitespace.characters]
tab = "→"
nbsp = "⍽"
nnbsp = "␣"

# indentation ===================================================================================

[editor.indent-guides]
render = true
character = "│"

# statusline ====================================================================================

[editor.statusline.mode]
normal = ">.<"
insert = ">o<"
select = ">v<"

# cursor =======================================================================================°

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# keymap =======================================================================================°

[keys.normal]
n = "move_char_left"
e = "move_visual_line_down"
i = "move_visual_line_up"
o = "move_char_right"

t = "insert_mode"
T = "insert_at_line_start"

k = "open_below"
K = "open_above"

f = "move_next_word_end"
F = "move_next_long_word_end"

h = "search_next"
H = "search_prev"

[keys.normal.g]
n = "goto_line_start"
o = "goto_line_end"

[keys.normal.space.w]
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"

[keys.normal.C-w]
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"

[keys.insert]
C-c = "normal_mode"
C-t = "normal_mode"

[keys.select]
n = "move_char_left"
e = "move_visual_line_down"
i = "move_visual_line_up"
o = "move_char_right"

t = "insert_mode"
T = "insert_at_line_start"

k = "open_below"
K = "open_above"

f = "move_next_word_end"
F = "move_next_long_word_end"

h = "search_next"
H = "search_prev"

E = "join_selections"
A-E = "join_selections_space"

I = "keep_selections"
A-I = "remove_selections"

[keys.normal.z]
e = "scroll_down"
i = "scroll_up"

[keys.normal.Z]
e = "scroll_down"
i = "scroll_up"
