[june]
from=june <me@koi.rip>
copy-to=Sent
cache-headers=true
pgp-auto-sign=true
pgp-self-encrypt=true
pgp-key-id=00F61623FB56BC5BB7094E634CE6C1172DF6BE79
source=imaps://me%40koi.rip@imap.purelymail.com:993
outgoing=smtps://me%40koi.rip@smtp.purelymail.com:465
source-cred-cmd=cat ~/.vault/email-password-me
outgoing-cred-cmd=cat ~/.vault/email-password-me

[noreply]
from=noreply@koi.rip
cache-headers=true
source=imaps://noreply%40koi.rip@imap.purelymail.com:993
outgoing=smtps://noreply%40koi.rip@smtp.purelymail.com:465
source-cred-cmd=cat ~/.vault/email-password-noreply
outgoing-cred-cmd=cat ~/.vault/email-password-noreply
