#!/usr/bin/env bash
set -euo pipefail

# Copyright 2026 june
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of the License at
#
#     https://git.koi.rip/koi/void/src/LICENSE
#
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.

EDITOR="${EDITOR:-vi}"

usage() {
  printf 'usage: %s [file ...]\n' "$(basename -- "$0")" >&2
  exit 1
}

run() {
  local file="$1"

  tmp="$(mktemp -- "doasvi.$(basename -- "$file").XXXXXX")"
  trap 'rm -f -- "$tmp"' RETURN

  if [[ -e "$file" ]]; then
    doas cat -- "$file" | tee -- "$tmp" >/dev/null
  fi

  "$EDITOR" "$tmp" || return "$?"

  if [[ -e "$file" ]] && cmp -s -- "$tmp" "$file"; then
    return 0
  fi
    
  cat -- "$tmp" | doas tee -- "$file" >/dev/null
}

main() {
  (( $# )) || usage

  local file status=0
  for file; do
    run "$file" || {
      status="$?"
      printf 'error: editing %s\n' "$file" >&2
    }
  done

  return "$status"
}

main "$@"
