theme = "evergarden-fall"

[font]
size = 16
family = "Maple Mono NF"

[display]
adapt_metadata_colors = "all"
decode_urls = true
nickname = [ "display-name", "pronouns" ]

[servers.liberachat]
server = "irc.libera.chat"
nickname = "junekot"
queries = [ "robinwobin" ]
monitor = [ "robinwobin" ]
channels = [ "#neovim", "#voidlinux", "#xbps" ]
[servers.liberachat.sasl.plain]
username = "junekot"
password_command = "cat ~/.secrets/irc-password"
disconnect_on_failure = true
[servers.liberachat.metadata]
avatar = "https://koi.rip/img/silly/pfp.png"
color = "#cbe3b3"
display-name = "june"
homepage = "https://koi.rip"
pronouns = "they/them"
status = "meowing :3"

[servers.oftc]
server = "irc.oftc.net"
nickname = "june"
nick_password_command = "cat ~/.secrets/irc-password"
channels = [ "#alpine-linux", "#alpine-devel", "#alpine-offtopic" ]
[servers.oftc.metadata]
avatar = "https://koi.rip/img/silly/pfp.png"
color = "#cbe3b3"
display-name = "june"
homepage = "https://koi.rip"
pronouns = "they/them"
status = "meowing :3"

[servers.rx]
server = "irc.runxiyu.org"
nickname = "june"
channels = [ "#chat" ]
[servers.rx.sasl.external]
cert = "~/.secrets/irc-rx.pem"
disconnect_on_failure = true
